version: '3'

services:
  web:
    build:
      context: ..
      dockerfile: ./docker/dev/Dockerfile
    command: ['sh', 'start.dev.sh']
    ports:
      - "$PORT:$PORT"
    volumes:
      - ..:/usr/src/app
    env_file:
      - ./dev/.env